// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v5.29.0
// source: activitypub.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestType int32

const (
	RequestType_PROFILE         RequestType = 0
	RequestType_READ_COLLECTION RequestType = 1
)

// Enum value maps for RequestType.
var (
	RequestType_name = map[int32]string{
		0: "PROFILE",
		1: "READ_COLLECTION",
	}
	RequestType_value = map[string]int32{
		"PROFILE":         0,
		"READ_COLLECTION": 1,
	}
)

func (x RequestType) Enum() *RequestType {
	p := new(RequestType)
	*p = x
	return p
}

func (x RequestType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RequestType) Descriptor() protoreflect.EnumDescriptor {
	return file_activitypub_proto_enumTypes[0].Descriptor()
}

func (RequestType) Type() protoreflect.EnumType {
	return &file_activitypub_proto_enumTypes[0]
}

func (x RequestType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RequestType.Descriptor instead.
func (RequestType) EnumDescriptor() ([]byte, []int) {
	return file_activitypub_proto_rawDescGZIP(), []int{0}
}

type Collection int32

const (
	Collection_INBOX     Collection = 0
	Collection_OUTBOX    Collection = 1
	Collection_FOLLOWERS Collection = 2
	Collection_FOLLOWING Collection = 3
	Collection_LIKED     Collection = 4
)

// Enum value maps for Collection.
var (
	Collection_name = map[int32]string{
		0: "INBOX",
		1: "OUTBOX",
		2: "FOLLOWERS",
		3: "FOLLOWING",
		4: "LIKED",
	}
	Collection_value = map[string]int32{
		"INBOX":     0,
		"OUTBOX":    1,
		"FOLLOWERS": 2,
		"FOLLOWING": 3,
		"LIKED":     4,
	}
)

func (x Collection) Enum() *Collection {
	p := new(Collection)
	*p = x
	return p
}

func (x Collection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Collection) Descriptor() protoreflect.EnumDescriptor {
	return file_activitypub_proto_enumTypes[1].Descriptor()
}

func (Collection) Type() protoreflect.EnumType {
	return &file_activitypub_proto_enumTypes[1]
}

func (x Collection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Collection.Descriptor instead.
func (Collection) EnumDescriptor() ([]byte, []int) {
	return file_activitypub_proto_rawDescGZIP(), []int{1}
}

type HTTPSignature struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Signature     string `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	Input         string `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	ContentDigest string `protobuf:"bytes,3,opt,name=contentDigest,proto3" json:"contentDigest,omitempty"`
}

func (x *HTTPSignature) Reset() {
	*x = HTTPSignature{}
	if protoimpl.UnsafeEnabled {
		mi := &file_activitypub_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HTTPSignature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTPSignature) ProtoMessage() {}

func (x *HTTPSignature) ProtoReflect() protoreflect.Message {
	mi := &file_activitypub_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTPSignature.ProtoReflect.Descriptor instead.
func (*HTTPSignature) Descriptor() ([]byte, []int) {
	return file_activitypub_proto_rawDescGZIP(), []int{0}
}

func (x *HTTPSignature) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *HTTPSignature) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

func (x *HTTPSignature) GetContentDigest() string {
	if x != nil {
		return x.ContentDigest
	}
	return ""
}

type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type          RequestType    `protobuf:"varint,1,opt,name=type,proto3,enum=activitypub.RequestType" json:"type,omitempty"`
	Collection    Collection     `protobuf:"varint,2,opt,name=collection,proto3,enum=activitypub.Collection" json:"collection,omitempty"`
	HttpSignature *HTTPSignature `protobuf:"bytes,3,opt,name=httpSignature,proto3" json:"httpSignature,omitempty"`
	Forwarded     string         `protobuf:"bytes,4,opt,name=forwarded,proto3" json:"forwarded,omitempty"`
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_activitypub_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_activitypub_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_activitypub_proto_rawDescGZIP(), []int{1}
}

func (x *Request) GetType() RequestType {
	if x != nil {
		return x.Type
	}
	return RequestType_PROFILE
}

func (x *Request) GetCollection() Collection {
	if x != nil {
		return x.Collection
	}
	return Collection_INBOX
}

func (x *Request) GetHttpSignature() *HTTPSignature {
	if x != nil {
		return x.HttpSignature
	}
	return nil
}

func (x *Request) GetForwarded() string {
	if x != nil {
		return x.Forwarded
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error  string `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	JsonLD string `protobuf:"bytes,2,opt,name=jsonLD,proto3" json:"jsonLD,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_activitypub_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_activitypub_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_activitypub_proto_rawDescGZIP(), []int{2}
}

func (x *Response) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Response) GetJsonLD() string {
	if x != nil {
		return x.JsonLD
	}
	return ""
}

var File_activitypub_proto protoreflect.FileDescriptor

var file_activitypub_proto_rawDesc = []byte{
	0x0a, 0x11, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x70, 0x75, 0x62, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x70, 0x75, 0x62,
	0x22, 0x69, 0x0a, 0x0d, 0x48, 0x54, 0x54, 0x50, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72,
	0x65, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x69, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x24, 0x0a, 0x0d, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x44, 0x69, 0x67, 0x65, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x44, 0x69, 0x67, 0x65, 0x73, 0x74, 0x22, 0xd0, 0x01, 0x0a, 0x07,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2c, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79,
	0x70, 0x75, 0x62, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x37, 0x0a, 0x0a, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x61, 0x63, 0x74, 0x69,
	0x76, 0x69, 0x74, 0x79, 0x70, 0x75, 0x62, 0x2e, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x0a, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x40,
	0x0a, 0x0d, 0x68, 0x74, 0x74, 0x70, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79,
	0x70, 0x75, 0x62, 0x2e, 0x48, 0x54, 0x54, 0x50, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72,
	0x65, 0x52, 0x0d, 0x68, 0x74, 0x74, 0x70, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65,
	0x12, 0x1c, 0x0a, 0x09, 0x66, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x65, 0x64, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x65, 0x64, 0x22, 0x38,
	0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x12, 0x16, 0x0a, 0x06, 0x6a, 0x73, 0x6f, 0x6e, 0x4c, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x6a, 0x73, 0x6f, 0x6e, 0x4c, 0x44, 0x2a, 0x2f, 0x0a, 0x0b, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x52, 0x4f, 0x46, 0x49,
	0x4c, 0x45, 0x10, 0x00, 0x12, 0x13, 0x0a, 0x0f, 0x52, 0x45, 0x41, 0x44, 0x5f, 0x43, 0x4f, 0x4c,
	0x4c, 0x45, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x01, 0x2a, 0x4c, 0x0a, 0x0a, 0x43, 0x6f, 0x6c,
	0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x09, 0x0a, 0x05, 0x49, 0x4e, 0x42, 0x4f, 0x58,
	0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x4f, 0x55, 0x54, 0x42, 0x4f, 0x58, 0x10, 0x01, 0x12, 0x0d,
	0x0a, 0x09, 0x46, 0x4f, 0x4c, 0x4c, 0x4f, 0x57, 0x45, 0x52, 0x53, 0x10, 0x02, 0x12, 0x0d, 0x0a,
	0x09, 0x46, 0x4f, 0x4c, 0x4c, 0x4f, 0x57, 0x49, 0x4e, 0x47, 0x10, 0x03, 0x12, 0x09, 0x0a, 0x05,
	0x4c, 0x49, 0x4b, 0x45, 0x44, 0x10, 0x04, 0x42, 0x2b, 0x5a, 0x29, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x63, 0x66, 0x77, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x70, 0x75,
	0x62, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_activitypub_proto_rawDescOnce sync.Once
	file_activitypub_proto_rawDescData = file_activitypub_proto_rawDesc
)

func file_activitypub_proto_rawDescGZIP() []byte {
	file_activitypub_proto_rawDescOnce.Do(func() {
		file_activitypub_proto_rawDescData = protoimpl.X.CompressGZIP(file_activitypub_proto_rawDescData)
	})
	return file_activitypub_proto_rawDescData
}

var file_activitypub_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_activitypub_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_activitypub_proto_goTypes = []interface{}{
	(RequestType)(0),      // 0: activitypub.RequestType
	(Collection)(0),       // 1: activitypub.Collection
	(*HTTPSignature)(nil), // 2: activitypub.HTTPSignature
	(*Request)(nil),       // 3: activitypub.Request
	(*Response)(nil),      // 4: activitypub.Response
}
var file_activitypub_proto_depIdxs = []int32{
	0, // 0: activitypub.Request.type:type_name -> activitypub.RequestType
	1, // 1: activitypub.Request.collection:type_name -> activitypub.Collection
	2, // 2: activitypub.Request.httpSignature:type_name -> activitypub.HTTPSignature
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_activitypub_proto_init() }
func file_activitypub_proto_init() {
	if File_activitypub_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_activitypub_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HTTPSignature); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_activitypub_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_activitypub_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_activitypub_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_activitypub_proto_goTypes,
		DependencyIndexes: file_activitypub_proto_depIdxs,
		EnumInfos:         file_activitypub_proto_enumTypes,
		MessageInfos:      file_activitypub_proto_msgTypes,
	}.Build()
	File_activitypub_proto = out.File
	file_activitypub_proto_rawDesc = nil
	file_activitypub_proto_goTypes = nil
	file_activitypub_proto_depIdxs = nil
}
