// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.12.4
// source: pkg/otter/pb/distStorage.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Allocator int32

const (
	Allocator_ALLOCATOR_UNSPECIFIED Allocator = 0
	Allocator_SPACE                 Allocator = 0
	Allocator_PINCOUNT              Allocator = 1
)

// Enum value maps for Allocator.
var (
	Allocator_name = map[int32]string{
		0: "ALLOCATOR_UNSPECIFIED",
		// Duplicate value: 0: "SPACE",
		1: "PINCOUNT",
	}
	Allocator_value = map[string]int32{
		"ALLOCATOR_UNSPECIFIED": 0,
		"SPACE":                 0,
		"PINCOUNT":              1,
	}
)

func (x Allocator) Enum() *Allocator {
	p := new(Allocator)
	*p = x
	return p
}

func (x Allocator) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Allocator) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_otter_pb_distStorage_proto_enumTypes[0].Descriptor()
}

func (Allocator) Type() protoreflect.EnumType {
	return &file_pkg_otter_pb_distStorage_proto_enumTypes[0]
}

func (x Allocator) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Allocator.Descriptor instead.
func (Allocator) EnumDescriptor() ([]byte, []int) {
	return file_pkg_otter_pb_distStorage_proto_rawDescGZIP(), []int{0}
}

type Chunker int32

const (
	Chunker_CHUNKER_UNSPECIFIED Chunker = 0
	Chunker_BOXO                Chunker = 0
)

// Enum value maps for Chunker.
var (
	Chunker_name = map[int32]string{
		0: "CHUNKER_UNSPECIFIED",
		// Duplicate value: 0: "BOXO",
	}
	Chunker_value = map[string]int32{
		"CHUNKER_UNSPECIFIED": 0,
		"BOXO":                0,
	}
)

func (x Chunker) Enum() *Chunker {
	p := new(Chunker)
	*p = x
	return p
}

func (x Chunker) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Chunker) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_otter_pb_distStorage_proto_enumTypes[1].Descriptor()
}

func (Chunker) Type() protoreflect.EnumType {
	return &file_pkg_otter_pb_distStorage_proto_enumTypes[1]
}

func (x Chunker) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Chunker.Descriptor instead.
func (Chunker) EnumDescriptor() ([]byte, []int) {
	return file_pkg_otter_pb_distStorage_proto_rawDescGZIP(), []int{1}
}

type PinState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pinned   bool `protobuf:"varint,1,opt,name=pinned,proto3" json:"pinned,omitempty"`
	Indirect bool `protobuf:"varint,2,opt,name=indirect,proto3" json:"indirect,omitempty"`
	Removing bool `protobuf:"varint,3,opt,name=removing,proto3" json:"removing,omitempty"`
}

func (x *PinState) Reset() {
	*x = PinState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_otter_pb_distStorage_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PinState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PinState) ProtoMessage() {}

func (x *PinState) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_otter_pb_distStorage_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PinState.ProtoReflect.Descriptor instead.
func (*PinState) Descriptor() ([]byte, []int) {
	return file_pkg_otter_pb_distStorage_proto_rawDescGZIP(), []int{0}
}

func (x *PinState) GetPinned() bool {
	if x != nil {
		return x.Pinned
	}
	return false
}

func (x *PinState) GetIndirect() bool {
	if x != nil {
		return x.Indirect
	}
	return false
}

func (x *PinState) GetRemoving() bool {
	if x != nil {
		return x.Removing
	}
	return false
}

type AddConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MinReplicas uint32    `protobuf:"varint,1,opt,name=minReplicas,proto3" json:"minReplicas,omitempty"`
	MaxReplicas uint32    `protobuf:"varint,2,opt,name=maxReplicas,proto3" json:"maxReplicas,omitempty"`
	Allocator   Allocator `protobuf:"varint,3,opt,name=Allocator,proto3,enum=distStorage.Allocator" json:"Allocator,omitempty"`
	Chunker     Chunker   `protobuf:"varint,4,opt,name=Chunker,proto3,enum=distStorage.Chunker" json:"Chunker,omitempty"`
	Shard       bool      `protobuf:"varint,5,opt,name=shard,proto3" json:"shard,omitempty"`
	Local       bool      `protobuf:"varint,6,opt,name=local,proto3" json:"local,omitempty"`
	Encrypted   bool      `protobuf:"varint,7,opt,name=encrypted,proto3" json:"encrypted,omitempty"`
}

func (x *AddConfig) Reset() {
	*x = AddConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_otter_pb_distStorage_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddConfig) ProtoMessage() {}

func (x *AddConfig) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_otter_pb_distStorage_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddConfig.ProtoReflect.Descriptor instead.
func (*AddConfig) Descriptor() ([]byte, []int) {
	return file_pkg_otter_pb_distStorage_proto_rawDescGZIP(), []int{1}
}

func (x *AddConfig) GetMinReplicas() uint32 {
	if x != nil {
		return x.MinReplicas
	}
	return 0
}

func (x *AddConfig) GetMaxReplicas() uint32 {
	if x != nil {
		return x.MaxReplicas
	}
	return 0
}

func (x *AddConfig) GetAllocator() Allocator {
	if x != nil {
		return x.Allocator
	}
	return Allocator_ALLOCATOR_UNSPECIFIED
}

func (x *AddConfig) GetChunker() Chunker {
	if x != nil {
		return x.Chunker
	}
	return Chunker_CHUNKER_UNSPECIFIED
}

func (x *AddConfig) GetShard() bool {
	if x != nil {
		return x.Shard
	}
	return false
}

func (x *AddConfig) GetLocal() bool {
	if x != nil {
		return x.Local
	}
	return false
}

func (x *AddConfig) GetEncrypted() bool {
	if x != nil {
		return x.Encrypted
	}
	return false
}

type PinInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TotalSize   uint64   `protobuf:"varint,1,opt,name=totalSize,proto3" json:"totalSize,omitempty"`
	PinPeers    []string `protobuf:"bytes,2,rep,name=pinPeers,proto3" json:"pinPeers,omitempty"`
	AddedTs     uint64   `protobuf:"varint,3,opt,name=addedTs,proto3" json:"addedTs,omitempty"`
	MinReplicas uint32   `protobuf:"varint,4,opt,name=minReplicas,proto3" json:"minReplicas,omitempty"`
	MaxReplicas uint32   `protobuf:"varint,5,opt,name=maxReplicas,proto3" json:"maxReplicas,omitempty"`
}

func (x *PinInfo) Reset() {
	*x = PinInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_otter_pb_distStorage_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PinInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PinInfo) ProtoMessage() {}

func (x *PinInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_otter_pb_distStorage_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PinInfo.ProtoReflect.Descriptor instead.
func (*PinInfo) Descriptor() ([]byte, []int) {
	return file_pkg_otter_pb_distStorage_proto_rawDescGZIP(), []int{2}
}

func (x *PinInfo) GetTotalSize() uint64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *PinInfo) GetPinPeers() []string {
	if x != nil {
		return x.PinPeers
	}
	return nil
}

func (x *PinInfo) GetAddedTs() uint64 {
	if x != nil {
		return x.AddedTs
	}
	return 0
}

func (x *PinInfo) GetMinReplicas() uint32 {
	if x != nil {
		return x.MinReplicas
	}
	return 0
}

func (x *PinInfo) GetMaxReplicas() uint32 {
	if x != nil {
		return x.MaxReplicas
	}
	return 0
}

var File_pkg_otter_pb_distStorage_proto protoreflect.FileDescriptor

var file_pkg_otter_pb_distStorage_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x70, 0x6b, 0x67, 0x2f, 0x6f, 0x74, 0x74, 0x65, 0x72, 0x2f, 0x70, 0x62, 0x2f, 0x64,
	0x69, 0x73, 0x74, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0b, 0x64, 0x69, 0x73, 0x74, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x22, 0x5a, 0x0a,
	0x08, 0x50, 0x69, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x69, 0x6e,
	0x6e, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x70, 0x69, 0x6e, 0x6e, 0x65,
	0x64, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6e, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x6e, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x12, 0x1a, 0x0a,
	0x08, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x69, 0x6e, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x08, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x69, 0x6e, 0x67, 0x22, 0xff, 0x01, 0x0a, 0x09, 0x41, 0x64,
	0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x20, 0x0a, 0x0b, 0x6d, 0x69, 0x6e, 0x52, 0x65,
	0x70, 0x6c, 0x69, 0x63, 0x61, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x6d, 0x69,
	0x6e, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x6d, 0x61, 0x78,
	0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b,
	0x6d, 0x61, 0x78, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x73, 0x12, 0x34, 0x0a, 0x09, 0x41,
	0x6c, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16,
	0x2e, 0x64, 0x69, 0x73, 0x74, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x41, 0x6c, 0x6c,
	0x6f, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x09, 0x41, 0x6c, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x6f,
	0x72, 0x12, 0x2e, 0x0a, 0x07, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x14, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65,
	0x2e, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x65, 0x72, 0x52, 0x07, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x65,
	0x72, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x68, 0x61, 0x72, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x05, 0x73, 0x68, 0x61, 0x72, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x6f, 0x63, 0x61, 0x6c,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x12, 0x1c, 0x0a,
	0x09, 0x65, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x65, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x09, 0x65, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x65, 0x64, 0x22, 0xa1, 0x01, 0x0a, 0x07,
	0x50, 0x69, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x53, 0x69, 0x7a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x69, 0x6e, 0x50, 0x65, 0x65, 0x72,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x70, 0x69, 0x6e, 0x50, 0x65, 0x65, 0x72,
	0x73, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x65, 0x64, 0x54, 0x73, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x07, 0x61, 0x64, 0x64, 0x65, 0x64, 0x54, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x6d,
	0x69, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x0b, 0x6d, 0x69, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x73, 0x12, 0x20, 0x0a,
	0x0b, 0x6d, 0x61, 0x78, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x73, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x0b, 0x6d, 0x61, 0x78, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x73, 0x2a,
	0x43, 0x0a, 0x09, 0x41, 0x6c, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x19, 0x0a, 0x15,
	0x41, 0x4c, 0x4c, 0x4f, 0x43, 0x41, 0x54, 0x4f, 0x52, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43,
	0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x53, 0x50, 0x41, 0x43, 0x45,
	0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x50, 0x49, 0x4e, 0x43, 0x4f, 0x55, 0x4e, 0x54, 0x10, 0x01,
	0x1a, 0x02, 0x10, 0x01, 0x2a, 0x30, 0x0a, 0x07, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x65, 0x72, 0x12,
	0x17, 0x0a, 0x13, 0x43, 0x48, 0x55, 0x4e, 0x4b, 0x45, 0x52, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45,
	0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x42, 0x4f, 0x58, 0x4f,
	0x10, 0x00, 0x1a, 0x02, 0x10, 0x01, 0x42, 0x24, 0x5a, 0x22, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x63, 0x66, 0x77, 0x2f, 0x6f, 0x74, 0x74, 0x65, 0x72, 0x2f,
	0x70, 0x6b, 0x67, 0x2f, 0x6f, 0x74, 0x74, 0x65, 0x72, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_otter_pb_distStorage_proto_rawDescOnce sync.Once
	file_pkg_otter_pb_distStorage_proto_rawDescData = file_pkg_otter_pb_distStorage_proto_rawDesc
)

func file_pkg_otter_pb_distStorage_proto_rawDescGZIP() []byte {
	file_pkg_otter_pb_distStorage_proto_rawDescOnce.Do(func() {
		file_pkg_otter_pb_distStorage_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_otter_pb_distStorage_proto_rawDescData)
	})
	return file_pkg_otter_pb_distStorage_proto_rawDescData
}

var file_pkg_otter_pb_distStorage_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pkg_otter_pb_distStorage_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pkg_otter_pb_distStorage_proto_goTypes = []interface{}{
	(Allocator)(0),    // 0: distStorage.Allocator
	(Chunker)(0),      // 1: distStorage.Chunker
	(*PinState)(nil),  // 2: distStorage.PinState
	(*AddConfig)(nil), // 3: distStorage.AddConfig
	(*PinInfo)(nil),   // 4: distStorage.PinInfo
}
var file_pkg_otter_pb_distStorage_proto_depIdxs = []int32{
	0, // 0: distStorage.AddConfig.Allocator:type_name -> distStorage.Allocator
	1, // 1: distStorage.AddConfig.Chunker:type_name -> distStorage.Chunker
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_otter_pb_distStorage_proto_init() }
func file_pkg_otter_pb_distStorage_proto_init() {
	if File_pkg_otter_pb_distStorage_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_otter_pb_distStorage_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PinState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_otter_pb_distStorage_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_otter_pb_distStorage_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PinInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_otter_pb_distStorage_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_otter_pb_distStorage_proto_goTypes,
		DependencyIndexes: file_pkg_otter_pb_distStorage_proto_depIdxs,
		EnumInfos:         file_pkg_otter_pb_distStorage_proto_enumTypes,
		MessageInfos:      file_pkg_otter_pb_distStorage_proto_msgTypes,
	}.Build()
	File_pkg_otter_pb_distStorage_proto = out.File
	file_pkg_otter_pb_distStorage_proto_rawDesc = nil
	file_pkg_otter_pb_distStorage_proto_goTypes = nil
	file_pkg_otter_pb_distStorage_proto_depIdxs = nil
}
