// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.12.4
// source: pkg/protos/petnames/pb/petnames.proto

package pb

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorCode int32

const (
	ErrorCode_SUCCESS              ErrorCode = 0
	ErrorCode_INTERNAL             ErrorCode = 1
	ErrorCode_OVER_MAX_PROBABILITY ErrorCode = 2
	ErrorCode_OVER_MAX_IDS         ErrorCode = 3
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0: "SUCCESS",
		1: "INTERNAL",
		2: "OVER_MAX_PROBABILITY",
		3: "OVER_MAX_IDS",
	}
	ErrorCode_value = map[string]int32{
		"SUCCESS":              0,
		"INTERNAL":             1,
		"OVER_MAX_PROBABILITY": 2,
		"OVER_MAX_IDS":         3,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_protos_petnames_pb_petnames_proto_enumTypes[0].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_pkg_protos_petnames_pb_petnames_proto_enumTypes[0]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_pkg_protos_petnames_pb_petnames_proto_rawDescGZIP(), []int{0}
}

type Name struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title      string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	FirstName  string   `protobuf:"bytes,3,opt,name=firstName,proto3" json:"firstName,omitempty"`
	MiddleName []string `protobuf:"bytes,4,rep,name=middleName,proto3" json:"middleName,omitempty"`
	LastName   string   `protobuf:"bytes,5,opt,name=lastName,proto3" json:"lastName,omitempty"`
}

func (x *Name) Reset() {
	*x = Name{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_protos_petnames_pb_petnames_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Name) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Name) ProtoMessage() {}

func (x *Name) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protos_petnames_pb_petnames_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Name.ProtoReflect.Descriptor instead.
func (*Name) Descriptor() ([]byte, []int) {
	return file_pkg_protos_petnames_pb_petnames_proto_rawDescGZIP(), []int{0}
}

func (x *Name) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Name) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Name) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *Name) GetMiddleName() []string {
	if x != nil {
		return x.MiddleName
	}
	return nil
}

func (x *Name) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

type Contact struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id               string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SharedName       *Name                `protobuf:"bytes,2,opt,name=sharedName,proto3" json:"sharedName,omitempty"`
	PrivateName      *Name                `protobuf:"bytes,3,opt,name=privateName,proto3" json:"privateName,omitempty"`
	Added            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=added,proto3" json:"added,omitempty"`
	LastUpdated      *timestamp.Timestamp `protobuf:"bytes,5,opt,name=lastUpdated,proto3" json:"lastUpdated,omitempty"`
	NumberOfContacts uint32               `protobuf:"varint,6,opt,name=numberOfContacts,proto3" json:"numberOfContacts,omitempty"`
}

func (x *Contact) Reset() {
	*x = Contact{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_protos_petnames_pb_petnames_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Contact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Contact) ProtoMessage() {}

func (x *Contact) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protos_petnames_pb_petnames_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Contact.ProtoReflect.Descriptor instead.
func (*Contact) Descriptor() ([]byte, []int) {
	return file_pkg_protos_petnames_pb_petnames_proto_rawDescGZIP(), []int{1}
}

func (x *Contact) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Contact) GetSharedName() *Name {
	if x != nil {
		return x.SharedName
	}
	return nil
}

func (x *Contact) GetPrivateName() *Name {
	if x != nil {
		return x.PrivateName
	}
	return nil
}

func (x *Contact) GetAdded() *timestamp.Timestamp {
	if x != nil {
		return x.Added
	}
	return nil
}

func (x *Contact) GetLastUpdated() *timestamp.Timestamp {
	if x != nil {
		return x.LastUpdated
	}
	return nil
}

func (x *Contact) GetNumberOfContacts() uint32 {
	if x != nil {
		return x.NumberOfContacts
	}
	return 0
}

type DOSName struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   *Name  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Degree uint32 `protobuf:"varint,2,opt,name=degree,proto3" json:"degree,omitempty"`
}

func (x *DOSName) Reset() {
	*x = DOSName{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_protos_petnames_pb_petnames_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DOSName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DOSName) ProtoMessage() {}

func (x *DOSName) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protos_petnames_pb_petnames_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DOSName.ProtoReflect.Descriptor instead.
func (*DOSName) Descriptor() ([]byte, []int) {
	return file_pkg_protos_petnames_pb_petnames_proto_rawDescGZIP(), []int{2}
}

func (x *DOSName) GetName() *Name {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *DOSName) GetDegree() uint32 {
	if x != nil {
		return x.Degree
	}
	return 0
}

type SetProposedNameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *SetProposedNameRequest) Reset() {
	*x = SetProposedNameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_protos_petnames_pb_petnames_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetProposedNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetProposedNameRequest) ProtoMessage() {}

func (x *SetProposedNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protos_petnames_pb_petnames_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetProposedNameRequest.ProtoReflect.Descriptor instead.
func (*SetProposedNameRequest) Descriptor() ([]byte, []int) {
	return file_pkg_protos_petnames_pb_petnames_proto_rawDescGZIP(), []int{3}
}

func (x *SetProposedNameRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SharedContact struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SharedName *Name  `protobuf:"bytes,2,opt,name=sharedName,proto3" json:"sharedName,omitempty"`
}

func (x *SharedContact) Reset() {
	*x = SharedContact{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_protos_petnames_pb_petnames_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SharedContact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SharedContact) ProtoMessage() {}

func (x *SharedContact) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protos_petnames_pb_petnames_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SharedContact.ProtoReflect.Descriptor instead.
func (*SharedContact) Descriptor() ([]byte, []int) {
	return file_pkg_protos_petnames_pb_petnames_proto_rawDescGZIP(), []int{4}
}

func (x *SharedContact) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SharedContact) GetSharedName() *Name {
	if x != nil {
		return x.SharedName
	}
	return nil
}

type LookupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                       []string `protobuf:"bytes,1,rep,name=id,proto3" json:"id,omitempty"`
	SuggestedNodeProbability float64  `protobuf:"fixed64,2,opt,name=suggestedNodeProbability,proto3" json:"suggestedNodeProbability,omitempty"`
}

func (x *LookupRequest) Reset() {
	*x = LookupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_protos_petnames_pb_petnames_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LookupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupRequest) ProtoMessage() {}

func (x *LookupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protos_petnames_pb_petnames_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupRequest.ProtoReflect.Descriptor instead.
func (*LookupRequest) Descriptor() ([]byte, []int) {
	return file_pkg_protos_petnames_pb_petnames_proto_rawDescGZIP(), []int{5}
}

func (x *LookupRequest) GetId() []string {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *LookupRequest) GetSuggestedNodeProbability() float64 {
	if x != nil {
		return x.SuggestedNodeProbability
	}
	return 0
}

type LookupResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error        ErrorCode        `protobuf:"varint,1,opt,name=error,proto3,enum=petnames.ErrorCode" json:"error,omitempty"`
	SharedNames  []*SharedContact `protobuf:"bytes,2,rep,name=sharedNames,proto3" json:"sharedNames,omitempty"`
	TryContactId []string         `protobuf:"bytes,3,rep,name=tryContactId,proto3" json:"tryContactId,omitempty"`
	ContactSize  uint64           `protobuf:"varint,4,opt,name=contactSize,proto3" json:"contactSize,omitempty"`
}

func (x *LookupResponse) Reset() {
	*x = LookupResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_protos_petnames_pb_petnames_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LookupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupResponse) ProtoMessage() {}

func (x *LookupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protos_petnames_pb_petnames_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupResponse.ProtoReflect.Descriptor instead.
func (*LookupResponse) Descriptor() ([]byte, []int) {
	return file_pkg_protos_petnames_pb_petnames_proto_rawDescGZIP(), []int{6}
}

func (x *LookupResponse) GetError() ErrorCode {
	if x != nil {
		return x.Error
	}
	return ErrorCode_SUCCESS
}

func (x *LookupResponse) GetSharedNames() []*SharedContact {
	if x != nil {
		return x.SharedNames
	}
	return nil
}

func (x *LookupResponse) GetTryContactId() []string {
	if x != nil {
		return x.TryContactId
	}
	return nil
}

func (x *LookupResponse) GetContactSize() uint64 {
	if x != nil {
		return x.ContactSize
	}
	return 0
}

var File_pkg_protos_petnames_pb_petnames_proto protoreflect.FileDescriptor

var file_pkg_protos_petnames_pb_petnames_proto_rawDesc = []byte{
	0x0a, 0x25, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x70, 0x65, 0x74,
	0x6e, 0x61, 0x6d, 0x65, 0x73, 0x2f, 0x70, 0x62, 0x2f, 0x70, 0x65, 0x74, 0x6e, 0x61, 0x6d, 0x65,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x65, 0x74, 0x6e, 0x61, 0x6d, 0x65,
	0x73, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x86, 0x01, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c,
	0x65, 0x12, 0x1c, 0x0a, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x1e, 0x0a, 0x0a, 0x6d, 0x69, 0x64, 0x64, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x0a, 0x6d, 0x69, 0x64, 0x64, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x97, 0x02, 0x0a, 0x07,
	0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2e, 0x0a, 0x0a, 0x73, 0x68, 0x61, 0x72, 0x65,
	0x64, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x65,
	0x74, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x2e, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x0a, 0x73, 0x68, 0x61,
	0x72, 0x65, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x30, 0x0a, 0x0b, 0x70, 0x72, 0x69, 0x76, 0x61,
	0x74, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70,
	0x65, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x2e, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x0b, 0x70, 0x72,
	0x69, 0x76, 0x61, 0x74, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x30, 0x0a, 0x05, 0x61, 0x64, 0x64,
	0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x52, 0x05, 0x61, 0x64, 0x64, 0x65, 0x64, 0x12, 0x3c, 0x0a, 0x0b, 0x6c,
	0x61, 0x73, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0b, 0x6c, 0x61,
	0x73, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x12, 0x2a, 0x0a, 0x10, 0x6e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x4f, 0x66, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x73, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x10, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x4f, 0x66, 0x43, 0x6f, 0x6e,
	0x74, 0x61, 0x63, 0x74, 0x73, 0x22, 0x45, 0x0a, 0x07, 0x44, 0x4f, 0x53, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x22, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e,
	0x2e, 0x70, 0x65, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x2e, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x65, 0x67, 0x72, 0x65, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x64, 0x65, 0x67, 0x72, 0x65, 0x65, 0x22, 0x2c, 0x0a, 0x16,
	0x53, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x65, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x4f, 0x0a, 0x0d, 0x53, 0x68,
	0x61, 0x72, 0x65, 0x64, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2e, 0x0a, 0x0a, 0x73,
	0x68, 0x61, 0x72, 0x65, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0e, 0x2e, 0x70, 0x65, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x2e, 0x4e, 0x61, 0x6d, 0x65, 0x52,
	0x0a, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x5b, 0x0a, 0x0d, 0x4c,
	0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x3a, 0x0a, 0x18,
	0x73, 0x75, 0x67, 0x67, 0x65, 0x73, 0x74, 0x65, 0x64, 0x4e, 0x6f, 0x64, 0x65, 0x50, 0x72, 0x6f,
	0x62, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x18,
	0x73, 0x75, 0x67, 0x67, 0x65, 0x73, 0x74, 0x65, 0x64, 0x4e, 0x6f, 0x64, 0x65, 0x50, 0x72, 0x6f,
	0x62, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x22, 0xbc, 0x01, 0x0a, 0x0e, 0x4c, 0x6f, 0x6f,
	0x6b, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x29, 0x0a, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x70, 0x65, 0x74,
	0x6e, 0x61, 0x6d, 0x65, 0x73, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x39, 0x0a, 0x0b, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64,
	0x4e, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x65,
	0x74, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x2e, 0x53, 0x68, 0x61, 0x72, 0x65, 0x64, 0x43, 0x6f, 0x6e,
	0x74, 0x61, 0x63, 0x74, 0x52, 0x0b, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x4e, 0x61, 0x6d, 0x65,
	0x73, 0x12, 0x22, 0x0a, 0x0c, 0x74, 0x72, 0x79, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x49,
	0x64, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x74, 0x72, 0x79, 0x43, 0x6f, 0x6e, 0x74,
	0x61, 0x63, 0x74, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74,
	0x53, 0x69, 0x7a, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x74,
	0x61, 0x63, 0x74, 0x53, 0x69, 0x7a, 0x65, 0x2a, 0x52, 0x0a, 0x09, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x43, 0x6f, 0x64, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10,
	0x00, 0x12, 0x0c, 0x0a, 0x08, 0x49, 0x4e, 0x54, 0x45, 0x52, 0x4e, 0x41, 0x4c, 0x10, 0x01, 0x12,
	0x18, 0x0a, 0x14, 0x4f, 0x56, 0x45, 0x52, 0x5f, 0x4d, 0x41, 0x58, 0x5f, 0x50, 0x52, 0x4f, 0x42,
	0x41, 0x42, 0x49, 0x4c, 0x49, 0x54, 0x59, 0x10, 0x02, 0x12, 0x10, 0x0a, 0x0c, 0x4f, 0x56, 0x45,
	0x52, 0x5f, 0x4d, 0x41, 0x58, 0x5f, 0x49, 0x44, 0x53, 0x10, 0x03, 0x42, 0x2e, 0x5a, 0x2c, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x63, 0x66, 0x77, 0x2f, 0x6f,
	0x74, 0x74, 0x65, 0x72, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f,
	0x70, 0x65, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_pkg_protos_petnames_pb_petnames_proto_rawDescOnce sync.Once
	file_pkg_protos_petnames_pb_petnames_proto_rawDescData = file_pkg_protos_petnames_pb_petnames_proto_rawDesc
)

func file_pkg_protos_petnames_pb_petnames_proto_rawDescGZIP() []byte {
	file_pkg_protos_petnames_pb_petnames_proto_rawDescOnce.Do(func() {
		file_pkg_protos_petnames_pb_petnames_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_protos_petnames_pb_petnames_proto_rawDescData)
	})
	return file_pkg_protos_petnames_pb_petnames_proto_rawDescData
}

var file_pkg_protos_petnames_pb_petnames_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_protos_petnames_pb_petnames_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_pkg_protos_petnames_pb_petnames_proto_goTypes = []interface{}{
	(ErrorCode)(0),                 // 0: petnames.ErrorCode
	(*Name)(nil),                   // 1: petnames.Name
	(*Contact)(nil),                // 2: petnames.Contact
	(*DOSName)(nil),                // 3: petnames.DOSName
	(*SetProposedNameRequest)(nil), // 4: petnames.SetProposedNameRequest
	(*SharedContact)(nil),          // 5: petnames.SharedContact
	(*LookupRequest)(nil),          // 6: petnames.LookupRequest
	(*LookupResponse)(nil),         // 7: petnames.LookupResponse
	(*timestamp.Timestamp)(nil),    // 8: google.protobuf.Timestamp
}
var file_pkg_protos_petnames_pb_petnames_proto_depIdxs = []int32{
	1, // 0: petnames.Contact.sharedName:type_name -> petnames.Name
	1, // 1: petnames.Contact.privateName:type_name -> petnames.Name
	8, // 2: petnames.Contact.added:type_name -> google.protobuf.Timestamp
	8, // 3: petnames.Contact.lastUpdated:type_name -> google.protobuf.Timestamp
	1, // 4: petnames.DOSName.name:type_name -> petnames.Name
	1, // 5: petnames.SharedContact.sharedName:type_name -> petnames.Name
	0, // 6: petnames.LookupResponse.error:type_name -> petnames.ErrorCode
	5, // 7: petnames.LookupResponse.sharedNames:type_name -> petnames.SharedContact
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_pkg_protos_petnames_pb_petnames_proto_init() }
func file_pkg_protos_petnames_pb_petnames_proto_init() {
	if File_pkg_protos_petnames_pb_petnames_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_protos_petnames_pb_petnames_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Name); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_protos_petnames_pb_petnames_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Contact); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_protos_petnames_pb_petnames_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DOSName); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_protos_petnames_pb_petnames_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetProposedNameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_protos_petnames_pb_petnames_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SharedContact); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_protos_petnames_pb_petnames_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LookupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_protos_petnames_pb_petnames_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LookupResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_protos_petnames_pb_petnames_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_protos_petnames_pb_petnames_proto_goTypes,
		DependencyIndexes: file_pkg_protos_petnames_pb_petnames_proto_depIdxs,
		EnumInfos:         file_pkg_protos_petnames_pb_petnames_proto_enumTypes,
		MessageInfos:      file_pkg_protos_petnames_pb_petnames_proto_msgTypes,
	}.Build()
	File_pkg_protos_petnames_pb_petnames_proto = out.File
	file_pkg_protos_petnames_pb_petnames_proto_rawDesc = nil
	file_pkg_protos_petnames_pb_petnames_proto_goTypes = nil
	file_pkg_protos_petnames_pb_petnames_proto_depIdxs = nil
}
