// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.12.4
// source: internal/ident4/pb/ident4.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorCode int32

const (
	ErrorCode_UNKNOWN                ErrorCode = 0
	ErrorCode_UNKNOWN_DEST_PUBLIC_ID ErrorCode = 1
	ErrorCode_UNKNOWN_DEST_PROTO     ErrorCode = 2
	ErrorCode_BAD_PUBLIC_ID          ErrorCode = 3
	ErrorCode_BAD_SIGNATURE          ErrorCode = 4
	ErrorCode_BAD_RANDOM             ErrorCode = 5
	ErrorCode_GO_AWAY                ErrorCode = 6
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0: "UNKNOWN",
		1: "UNKNOWN_DEST_PUBLIC_ID",
		2: "UNKNOWN_DEST_PROTO",
		3: "BAD_PUBLIC_ID",
		4: "BAD_SIGNATURE",
		5: "BAD_RANDOM",
		6: "GO_AWAY",
	}
	ErrorCode_value = map[string]int32{
		"UNKNOWN":                0,
		"UNKNOWN_DEST_PUBLIC_ID": 1,
		"UNKNOWN_DEST_PROTO":     2,
		"BAD_PUBLIC_ID":          3,
		"BAD_SIGNATURE":          4,
		"BAD_RANDOM":             5,
		"GO_AWAY":                6,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_ident4_pb_ident4_proto_enumTypes[0].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_internal_ident4_pb_ident4_proto_enumTypes[0]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_internal_ident4_pb_ident4_proto_rawDescGZIP(), []int{0}
}

type Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Packet:
	//	*Message_Hello
	//	*Message_HelloSig
	//	*Message_OkSig
	//	*Message_Ok
	//	*Message_Error
	Packet isMessage_Packet `protobuf_oneof:"packet"`
}

func (x *Message) Reset() {
	*x = Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_ident4_pb_ident4_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ident4_pb_ident4_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_internal_ident4_pb_ident4_proto_rawDescGZIP(), []int{0}
}

func (m *Message) GetPacket() isMessage_Packet {
	if m != nil {
		return m.Packet
	}
	return nil
}

func (x *Message) GetHello() *Hello {
	if x, ok := x.GetPacket().(*Message_Hello); ok {
		return x.Hello
	}
	return nil
}

func (x *Message) GetHelloSig() *HelloSig {
	if x, ok := x.GetPacket().(*Message_HelloSig); ok {
		return x.HelloSig
	}
	return nil
}

func (x *Message) GetOkSig() *Sig {
	if x, ok := x.GetPacket().(*Message_OkSig); ok {
		return x.OkSig
	}
	return nil
}

func (x *Message) GetOk() *Ok {
	if x, ok := x.GetPacket().(*Message_Ok); ok {
		return x.Ok
	}
	return nil
}

func (x *Message) GetError() *Error {
	if x, ok := x.GetPacket().(*Message_Error); ok {
		return x.Error
	}
	return nil
}

type isMessage_Packet interface {
	isMessage_Packet()
}

type Message_Hello struct {
	Hello *Hello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type Message_HelloSig struct {
	HelloSig *HelloSig `protobuf:"bytes,2,opt,name=helloSig,proto3,oneof"`
}

type Message_OkSig struct {
	OkSig *Sig `protobuf:"bytes,3,opt,name=okSig,proto3,oneof"`
}

type Message_Ok struct {
	Ok *Ok `protobuf:"bytes,4,opt,name=ok,proto3,oneof"`
}

type Message_Error struct {
	Error *Error `protobuf:"bytes,5,opt,name=error,proto3,oneof"`
}

func (*Message_Hello) isMessage_Packet() {}

func (*Message_HelloSig) isMessage_Packet() {}

func (*Message_OkSig) isMessage_Packet() {}

func (*Message_Ok) isMessage_Packet() {}

func (*Message_Error) isMessage_Packet() {}

type Hello struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Random       []byte `protobuf:"bytes,1,opt,name=random,proto3" json:"random,omitempty"`
	SrcPublicID  string `protobuf:"bytes,2,opt,name=srcPublicID,proto3" json:"srcPublicID,omitempty"`
	DestPublicID string `protobuf:"bytes,3,opt,name=destPublicID,proto3" json:"destPublicID,omitempty"`
	NextProto    string `protobuf:"bytes,4,opt,name=nextProto,proto3" json:"nextProto,omitempty"`
}

func (x *Hello) Reset() {
	*x = Hello{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_ident4_pb_ident4_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ident4_pb_ident4_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_internal_ident4_pb_ident4_proto_rawDescGZIP(), []int{1}
}

func (x *Hello) GetRandom() []byte {
	if x != nil {
		return x.Random
	}
	return nil
}

func (x *Hello) GetSrcPublicID() string {
	if x != nil {
		return x.SrcPublicID
	}
	return ""
}

func (x *Hello) GetDestPublicID() string {
	if x != nil {
		return x.DestPublicID
	}
	return ""
}

func (x *Hello) GetNextProto() string {
	if x != nil {
		return x.NextProto
	}
	return ""
}

type HelloSig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Random []byte `protobuf:"bytes,1,opt,name=random,proto3" json:"random,omitempty"`
	Sig    *Sig   `protobuf:"bytes,2,opt,name=sig,proto3" json:"sig,omitempty"`
}

func (x *HelloSig) Reset() {
	*x = HelloSig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_ident4_pb_ident4_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloSig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloSig) ProtoMessage() {}

func (x *HelloSig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ident4_pb_ident4_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloSig.ProtoReflect.Descriptor instead.
func (*HelloSig) Descriptor() ([]byte, []int) {
	return file_internal_ident4_pb_ident4_proto_rawDescGZIP(), []int{2}
}

func (x *HelloSig) GetRandom() []byte {
	if x != nil {
		return x.Random
	}
	return nil
}

func (x *HelloSig) GetSig() *Sig {
	if x != nil {
		return x.Sig
	}
	return nil
}

type Sig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Signature []byte `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (x *Sig) Reset() {
	*x = Sig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_ident4_pb_ident4_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Sig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sig) ProtoMessage() {}

func (x *Sig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ident4_pb_ident4_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sig.ProtoReflect.Descriptor instead.
func (*Sig) Descriptor() ([]byte, []int) {
	return file_internal_ident4_pb_ident4_proto_rawDescGZIP(), []int{3}
}

func (x *Sig) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type Ok struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Ok) Reset() {
	*x = Ok{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_ident4_pb_ident4_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ok) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ok) ProtoMessage() {}

func (x *Ok) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ident4_pb_ident4_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ok.ProtoReflect.Descriptor instead.
func (*Ok) Descriptor() ([]byte, []int) {
	return file_internal_ident4_pb_ident4_proto_rawDescGZIP(), []int{4}
}

type Error struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code ErrorCode `protobuf:"varint,1,opt,name=code,proto3,enum=ident4.ErrorCode" json:"code,omitempty"`
	Msg  string    `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *Error) Reset() {
	*x = Error{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_ident4_pb_ident4_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ident4_pb_ident4_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_internal_ident4_pb_ident4_proto_rawDescGZIP(), []int{5}
}

func (x *Error) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_UNKNOWN
}

func (x *Error) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_internal_ident4_pb_ident4_proto protoreflect.FileDescriptor

var file_internal_ident4_pb_ident4_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x69, 0x64, 0x65, 0x6e, 0x74,
	0x34, 0x2f, 0x70, 0x62, 0x2f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x34, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x06, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x34, 0x22, 0xd4, 0x01, 0x0a, 0x07, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x25, 0x0a, 0x05, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x34, 0x2e, 0x48, 0x65,
	0x6c, 0x6c, 0x6f, 0x48, 0x00, 0x52, 0x05, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x2e, 0x0a, 0x08,
	0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x53, 0x69, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10,
	0x2e, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x34, 0x2e, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x53, 0x69, 0x67,
	0x48, 0x00, 0x52, 0x08, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x53, 0x69, 0x67, 0x12, 0x23, 0x0a, 0x05,
	0x6f, 0x6b, 0x53, 0x69, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x69, 0x64,
	0x65, 0x6e, 0x74, 0x34, 0x2e, 0x53, 0x69, 0x67, 0x48, 0x00, 0x52, 0x05, 0x6f, 0x6b, 0x53, 0x69,
	0x67, 0x12, 0x1c, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e,
	0x69, 0x64, 0x65, 0x6e, 0x74, 0x34, 0x2e, 0x4f, 0x6b, 0x48, 0x00, 0x52, 0x02, 0x6f, 0x6b, 0x12,
	0x25, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d,
	0x2e, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x34, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x48, 0x00, 0x52,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x42, 0x08, 0x0a, 0x06, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74,
	0x22, 0x83, 0x01, 0x0a, 0x05, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x61,
	0x6e, 0x64, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x72, 0x61, 0x6e, 0x64,
	0x6f, 0x6d, 0x12, 0x20, 0x0a, 0x0b, 0x73, 0x72, 0x63, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x49,
	0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x72, 0x63, 0x50, 0x75, 0x62, 0x6c,
	0x69, 0x63, 0x49, 0x44, 0x12, 0x22, 0x0a, 0x0c, 0x64, 0x65, 0x73, 0x74, 0x50, 0x75, 0x62, 0x6c,
	0x69, 0x63, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x64, 0x65, 0x73, 0x74,
	0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x65, 0x78, 0x74,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x65, 0x78,
	0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x41, 0x0a, 0x08, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x53,
	0x69, 0x67, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x06, 0x72, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x12, 0x1d, 0x0a, 0x03, 0x73, 0x69,
	0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x34,
	0x2e, 0x53, 0x69, 0x67, 0x52, 0x03, 0x73, 0x69, 0x67, 0x22, 0x23, 0x0a, 0x03, 0x53, 0x69, 0x67,
	0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x22, 0x04,
	0x0a, 0x02, 0x4f, 0x6b, 0x22, 0x40, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x25, 0x0a,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x69, 0x64,
	0x65, 0x6e, 0x74, 0x34, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x2a, 0x8f, 0x01, 0x0a, 0x09, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x43, 0x6f, 0x64, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10,
	0x00, 0x12, 0x1a, 0x0a, 0x16, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x5f, 0x44, 0x45, 0x53,
	0x54, 0x5f, 0x50, 0x55, 0x42, 0x4c, 0x49, 0x43, 0x5f, 0x49, 0x44, 0x10, 0x01, 0x12, 0x16, 0x0a,
	0x12, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x5f, 0x44, 0x45, 0x53, 0x54, 0x5f, 0x50, 0x52,
	0x4f, 0x54, 0x4f, 0x10, 0x02, 0x12, 0x11, 0x0a, 0x0d, 0x42, 0x41, 0x44, 0x5f, 0x50, 0x55, 0x42,
	0x4c, 0x49, 0x43, 0x5f, 0x49, 0x44, 0x10, 0x03, 0x12, 0x11, 0x0a, 0x0d, 0x42, 0x41, 0x44, 0x5f,
	0x53, 0x49, 0x47, 0x4e, 0x41, 0x54, 0x55, 0x52, 0x45, 0x10, 0x04, 0x12, 0x0e, 0x0a, 0x0a, 0x42,
	0x41, 0x44, 0x5f, 0x52, 0x41, 0x4e, 0x44, 0x4f, 0x4d, 0x10, 0x05, 0x12, 0x0b, 0x0a, 0x07, 0x47,
	0x4f, 0x5f, 0x41, 0x57, 0x41, 0x59, 0x10, 0x06, 0x42, 0x2a, 0x5a, 0x28, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x63, 0x66, 0x77, 0x2f, 0x6f, 0x74, 0x74, 0x65,
	0x72, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x69, 0x64, 0x65, 0x6e, 0x74,
	0x34, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_ident4_pb_ident4_proto_rawDescOnce sync.Once
	file_internal_ident4_pb_ident4_proto_rawDescData = file_internal_ident4_pb_ident4_proto_rawDesc
)

func file_internal_ident4_pb_ident4_proto_rawDescGZIP() []byte {
	file_internal_ident4_pb_ident4_proto_rawDescOnce.Do(func() {
		file_internal_ident4_pb_ident4_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_ident4_pb_ident4_proto_rawDescData)
	})
	return file_internal_ident4_pb_ident4_proto_rawDescData
}

var file_internal_ident4_pb_ident4_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_ident4_pb_ident4_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_internal_ident4_pb_ident4_proto_goTypes = []interface{}{
	(ErrorCode)(0),   // 0: ident4.ErrorCode
	(*Message)(nil),  // 1: ident4.Message
	(*Hello)(nil),    // 2: ident4.Hello
	(*HelloSig)(nil), // 3: ident4.HelloSig
	(*Sig)(nil),      // 4: ident4.Sig
	(*Ok)(nil),       // 5: ident4.Ok
	(*Error)(nil),    // 6: ident4.Error
}
var file_internal_ident4_pb_ident4_proto_depIdxs = []int32{
	2, // 0: ident4.Message.hello:type_name -> ident4.Hello
	3, // 1: ident4.Message.helloSig:type_name -> ident4.HelloSig
	4, // 2: ident4.Message.okSig:type_name -> ident4.Sig
	5, // 3: ident4.Message.ok:type_name -> ident4.Ok
	6, // 4: ident4.Message.error:type_name -> ident4.Error
	4, // 5: ident4.HelloSig.sig:type_name -> ident4.Sig
	0, // 6: ident4.Error.code:type_name -> ident4.ErrorCode
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_internal_ident4_pb_ident4_proto_init() }
func file_internal_ident4_pb_ident4_proto_init() {
	if File_internal_ident4_pb_ident4_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_ident4_pb_ident4_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_ident4_pb_ident4_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Hello); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_ident4_pb_ident4_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelloSig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_ident4_pb_ident4_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Sig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_ident4_pb_ident4_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ok); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_ident4_pb_ident4_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Error); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_internal_ident4_pb_ident4_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Message_Hello)(nil),
		(*Message_HelloSig)(nil),
		(*Message_OkSig)(nil),
		(*Message_Ok)(nil),
		(*Message_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_ident4_pb_ident4_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_ident4_pb_ident4_proto_goTypes,
		DependencyIndexes: file_internal_ident4_pb_ident4_proto_depIdxs,
		EnumInfos:         file_internal_ident4_pb_ident4_proto_enumTypes,
		MessageInfos:      file_internal_ident4_pb_ident4_proto_msgTypes,
	}.Build()
	File_internal_ident4_pb_ident4_proto = out.File
	file_internal_ident4_pb_ident4_proto_rawDesc = nil
	file_internal_ident4_pb_ident4_proto_goTypes = nil
	file_internal_ident4_pb_ident4_proto_depIdxs = nil
}
